- name: install apache and php package on Ubuntu
  tags: apache,apache2,ubuntu
  apt:
     name:
       - apache2
       - libapache2-mod-php
     state: latest

  when: ansible_distribution == "Ubuntu"

- name: install apache and php package on Centos
  tags: apache,centos,httpd
  dnf:
    name:
      - httpd
      - php
    state: latest

  when: ansible_distribution == "CentOS"

- name: Copy default html files for site
  tags: apache,apache2,httpd
  copy:
    src: index.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644

